 development:
   adapter: mysql2
   encoding: utf8
   database: night_development
   username: root
   password:
   host: localhost

 test:
   adapter: mysql2
   encoding: utf8
   database: night_test
   username: root
   password:
   host: localhost
